name: weuniba_flutter
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.0
  mobile_scanner: ^3.5.5
  cupertino_icons: ^1.0.8
  flutter_pdfview: ^1.2.5
  path_provider: ^2.0.15
  http: ^0.13.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # Abilita le icone Material
  uses-material-design: true

  # Elenco degli asset usati nell'app
  assets:
    - assets/buttons/
    - assets/lucky_charms/
    - assets/audio/
    - assets/learning_materials/
    - assets/badges/
    - assets/coin/
    - assets/avatar/
    - assets/avatar/accessories/
    - assets/avatar/complexion/black/
    - assets/avatar/complexion/white/
    - assets/map/campus_map.png
    - assets/avatar/accessories/avatar_with_occhiali/
    - assets/logo/
